#ifndef __EnClavGui__
#define __EnClavGui__

/**
@file
Subclass of EnClavGuiBase, which is generated by wxFormBuilder.
*/

#include "EnClavGuiBase.h"

/** Implementing EnClavGuiBase */
class EnClavGui : public EnClavGuiBase
{
protected:
	// Handlers for EnClavGuiBase events.
	void OnMenuQuitter( wxCommandEvent& event );
	void OnMenuPreferences( wxCommandEvent& event );
	void OnMenuApropos( wxCommandEvent& event );
	void OnButtonRefreshJackClick( wxCommandEvent& event );
	void OnCbIncludePS2Check( wxCommandEvent& event );
	void OnButtonDetectClClick( wxCommandEvent& event );
	
public:
	/** Constructor */
	EnClavGui( wxWindow* parent );
};

#endif // __EnClavGui__
